name: Publish Package (npm + GitHub Packages)

on:
  release:
    types: [published]

concurrency:
  group: publish-${{ github.event.release.tag_name }}
  cancel-in-progress: false

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write        # 推送 GitHub Packages
      id-token: write        # npm provenance
    env:
      PKG_DIR: packages/cursor-with
    steps:
      # ---------- 基础准备 ----------
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Enable corepack & install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@9.0.0 --activate
          echo "$(dirname "$(command -v pnpm)")" >> $GITHUB_PATH

      # ---------- 安装 & 构建 ----------
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build package
        run: pnpm build:core

      # ---------- 版本校验 ----------
      - name: Verify version
        run: |
          TAG="${{ github.event.release.tag_name }}"
          VER="v$(node -p "require('./${PKG_DIR}/package.json').version")"
          if [ "$VER" != "$TAG" ]; then
            echo "Version mismatch: $VER vs $TAG"; exit 1
          fi

      # ---------- 1. 去 scope 推 npm ----------
      - name: De-scope package.json for npm
        working-directory: ${{ env.PKG_DIR }}
        run: |
          cp package.json package.json.bak
          node -e "
            const p = JSON.parse(require('fs').readFileSync('package.json','utf8'));
            p.name = 'cursorwith-ts';
            delete p.publishConfig;
            require('fs').writeFileSync('package.json', JSON.stringify(p, null, 2));
          "

      - name: Setup npm auth
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to npm
        working-directory: ${{ env.PKG_DIR }}
        run: npm publish --access public --provenance

      # ---------- 2. 还原 scoped 推 GitHub Packages ----------
      - name: Restore scoped package.json
        working-directory: ${{ env.PKG_DIR }}
        run: mv package.json.bak package.json

      - name: Setup GitHub Packages auth
        working-directory: ${{ env.PKG_DIR }}
        run: |
          echo "@leoncry:registry=https://npm.pkg.github.com" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" >> .npmrc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to GitHub Packages
        working-directory: ${{ env.PKG_DIR }}
        run: npm publish --provenance

      # ---------- 任务总结 ----------
      - name: Job summary
        run: |
          echo "| Registry | Package |" >> $GITHUB_STEP_SUMMARY
          echo "|----------|---------|" >> $GITHUB_STEP_SUMMARY
          echo "| npm | [cursorwith-ts](https://www.npmjs.com/package/cursorwith-ts) |" >> $GITHUB_STEP_SUMMARY
          echo "| GitHub Packages | [@leoncry/cursorwith-ts](https://github.com/leoncry/cursorwith-ts/pkgs/npm/cursorwith-ts) |" >> $GITHUB_STEP_SUMMARY