name: Publish Package (npm)

on:
  release:
    types: [published]

concurrency:
  group: publish-${{ github.event.release.tag_name }}
  cancel-in-progress: false

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write   # npm provenance
    env:
      PKG_DIR: packages/cursor-with
    steps:
      # ---------- 基础准备 ----------
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Enable corepack & install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@9.0.0 --activate
          echo "$(dirname "$(command -v pnpm)")" >> $GITHUB_PATH

      # ---------- 安装 & 构建 ----------
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build package
        run: pnpm build:core

      # ---------- 版本校验 ----------
      - name: Verify version
        run: |
          TAG="${{ github.event.release.tag_name }}"
          VER="v$(node -p "require('./${PKG_DIR}/package.json').version")"
          if [ "$VER" != "$TAG" ]; then
            echo "Version mismatch: $VER vs $TAG"; exit 1
          fi

      # ---------- 发布到 npm ----------
      - name: Setup npm auth
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to npm
        working-directory: ${{ env.PKG_DIR }}
        run: npm publish --access public --provenance

      # ---------- 任务总结 ----------
      - name: Job summary
        run: |
          echo "| Registry | Package |" >> $GITHUB_STEP_SUMMARY
          echo "|----------|---------|" >> $GITHUB_STEP_SUMMARY
          echo "| npm | [cursorwith-ts](https://www.npmjs.com/package/cursorwith-ts) |" >> $GITHUB_STEP_SUMMARY