name: Publish Package (npm + GitHub Packages)

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry run (skip actual publish)'
        required: false
        default: 'false'

concurrency:
  group: publish-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write   # for GitHub Packages
      id-token: write   # provenance / OIDC (optional, for npm provenance)
    env:
      # Workspace relative path to the package directory
      PKG_DIR: packages/cursor-with
      SCOPE: '@leoncry'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build package
        run: pnpm build:core

      - name: Show package info
        run: |
          node -p "require('./${PKG_DIR}/package.json').name + ' v' + require('./${PKG_DIR}/package.json').version"

      - name: Prepare npm auth
        if: ${{ inputs.dry_run != 'true' }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to npm
        if: ${{ inputs.dry_run != 'true' }}
        working-directory: ${{ env.PKG_DIR }}
        run: |
          npm publish --access public --registry=https://registry.npmjs.org/

      - name: Prepare GitHub Packages auth
        if: ${{ inputs.dry_run != 'true' }}
        run: |
          echo "${SCOPE}:registry=https://npm.pkg.github.com" >> ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" >> ~/.npmrc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN || secrets.GH_PKG_TOKEN }}

      - name: Publish to GitHub Packages
        if: ${{ inputs.dry_run != 'true' }}
        working-directory: ${{ env.PKG_DIR }}
        run: |
          npm publish --access public --registry=https://npm.pkg.github.com

      - name: Dry-run notice
        if: ${{ inputs.dry_run == 'true' }}
        run: |
          echo "Dry run enabled: build completed, skipping publish steps."

      - name: Summary
        run: |
          echo "### Publish summary" >> $GITHUB_STEP_SUMMARY
          echo "Tag: $GITHUB_REF" >> $GITHUB_STEP_SUMMARY
          echo "Package: $(node -p \"require('./${PKG_DIR}/package.json').name\")" >> $GITHUB_STEP_SUMMARY
          echo "Version: $(node -p \"require('./${PKG_DIR}/package.json').version\")" >> $GITHUB_STEP_SUMMARY
          if [ "${{ inputs.dry_run }}" = "true" ]; then echo "Mode: DRY RUN" >> $GITHUB_STEP_SUMMARY; else echo "Mode: PUBLISH" >> $GITHUB_STEP_SUMMARY; fi
